/* Generated by Cython 0.29.32 */

#ifndef __PYX_HAVE__NNApp__src__CythonNeuralNetwork__NeuralNetwork
#define __PYX_HAVE__NNApp__src__CythonNeuralNetwork__NeuralNetwork

#include "Python.h"

#ifndef __PYX_HAVE_API__NNApp__src__CythonNeuralNetwork__NeuralNetwork

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C int K;

#endif /* !__PYX_HAVE_API__NNApp__src__CythonNeuralNetwork__NeuralNetwork */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initNeuralNetwork(void);
#else
PyMODINIT_FUNC PyInit_NeuralNetwork(void);
#endif

#endif /* !__PYX_HAVE__NNApp__src__CythonNeuralNetwork__NeuralNetwork */
